### ISSUE TITLE
biometric data type

### ISSUE THREAD

**Issue by DiTo97** [ichason/BiometricKeyStoreSample#1]
what kind of biometric data have u been working on?

**Comment by ichason** [comment]
很久之前搞的这个东西，仅仅是处理Android指纹

**Comment by DiTo97** [comment]
makes sense!

would you be interested in a collaboration on a similar topic handling biometric data, collected from smartphones and smart wearables?

**Comment by ichason** [comment]
Of course, what can I do?

**Comment by ichason** [comment]
hello？

**Comment by DiTo97** [comment]
@ichason, email me at fede97.minutoli@gmail.com or DM me on LinkedIn, so we can schedule a short meeting!
